import Head from 'next/head'
import Image from 'next/image'
import { useTheme } from 'next-themes'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { CreateRoom, Header, JoinRoom } from '../components'

export default function Home() {
  const [mode, setMode] = useState(false)
  const [mounted, setMounted] = useState(false)
  const { theme, setTheme } = useTheme()

  // When mounted on client, now we can show the UI
  useEffect(() => setMounted(true), [])
  if (!mounted) return null

  console.log({ theme })
  return (
    <>
      <div className={styles.container}>
        <Header theme={theme} toggleTheme={() => setTheme(theme === 'dark' ? 'light' : 'dark')} />
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={`${styles.main} ${mode ? styles.mainToggled : ''}`}>
          <JoinRoom toggleShow={() => setMode(true)} />
          <CreateRoom toggleShow={() => setMode(false)} />
          <div className={`${styles.imageContainer} ${mode ? styles.imageContainerAnimated : ''}`}>
            <Image
              src="/Spinach.webp"
              alt="hero"
              width="100%"
              height="100%"
              layout="fill"
              objectFit="cover"
              placeholder="blur"
              blurDataURL="data:image/webp;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN88/drPQAJGgNf5ggxWwAAAABJRU5ErkJggg=="
              priority
            />
          </div>
        </main>
      </div>
    </>
  )
}
