import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { useTheme } from 'next-themes'
import io from 'socket.io-client'
import { CreateRoom, Header, JoinRoom } from '../components'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [mode, setMode] = useState(false)
  const [mounted, setMounted] = useState(false)
  const [socket, setSocket] = useState(null)
  const [connection, setConnection] = useState(null)

  const { theme, setTheme } = useTheme()

  useEffect(() => {
    const newSocket = io('http://localhost:3001')
    setSocket(newSocket)
    newSocket.on('connect', () => {
      console.log('connected')
    })
    return () => newSocket.close()
  }, [setSocket])

  useEffect(() => console.log(connection), [connection])

  // When mounted on client, now we can show the UI
  useEffect(() => setMounted(true), [])
  if (!mounted) return null

  return (
    <>
      <div className={styles.container}>
        <Header theme={theme} toggleTheme={() => setTheme(theme === 'dark' ? 'light' : 'dark')} />
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={`${styles.main} ${mode ? styles.mainToggled : ''}`}>
          <JoinRoom
            toggleShow={() => setMode(true)}
            onSubmit={({ name, room }) =>
              socket.emit('join_room', { name, room }, (callback) => setConnection(callback))
            }
          />
          <CreateRoom
            toggleShow={() => setMode(false)}
            onSubmit={({ name, password }) =>
              socket.emit('create_room', { name, password }, (callback) => setConnection(callback))
            }
          />
          <div className={`${styles.imageContainer} ${mode ? styles.imageContainerAnimated : ''}`}>
            <Image
              src="/Spinach.webp"
              alt="hero"
              layout="fill"
              objectFit="cover"
              placeholder="blur"
              blurDataURL="data:image/webp;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN88/frfwAJmgPfIAPobgAAAABJRU5ErkJggg=="
              priority
            />
          </div>
        </main>
      </div>
    </>
  )
}
